version: "3.8"
services:
    userservice:
        container_name: user-service
        build: .
        ports:
            - "8000:80"
        volumes: 
            - "/Ephata.User.WebAPI/appsettings.Development.json:/appsettings.Development.json"
        depends_on:
            - sqlserver
    sqlserver:
        container_name: sql-service
        environment:
            SA_PASSWORD: "Admin@123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports: 
            - "1439:1433"
        build: 
            context: .
            dockerfile: Dockerfile.Migration
  