version: "3.8"
services:
    userservice:
        container_name: user-service
        build: .
        ports:
            - "8000:80"
        environment: 
            ASPNETCORE_ENVIRONMENT: 'Development'
        volumes: 
            - "/Ephata.User.WebAPI/appsettings.Development.json:/appsettings.Development.json"
            - "/Ephata.User.WebAPI/appsettings.json:/appsettings.json"
        depends_on:
            - postgres
    postgres:
        container_name: postgres-service
        image: postgres:latest
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        volumes:
            - './initdb:/docker-entrypoint-initdb.d'
        ports:
            - "5432:5432"
        restart: always
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]